#include "VansSceneReflectionProbeConfigReader.h"

#include "../AssetCore/Serialization/VansSerializedValueAccess.h"

#include <cstddef>

namespace Vans
{
namespace
{
const VansSerializedValue* ReadObjectField(const VansSerializedValue& object, const char* key)
{
	const VansSerializedValue* field = FindObjectField(object, key);
	return field && field->kind == VansSerializedValue::Kind::Object ? field : nullptr;
}

const VansSerializedValue* ReadArrayField(const VansSerializedValue& object, const char* key)
{
	const VansSerializedValue* field = FindObjectField(object, key);
	return field && field->kind == VansSerializedValue::Kind::Array ? field : nullptr;
}

std::optional<float> ReadOptionalFloatField(const VansSerializedValue& object, const char* key)
{
	const VansSerializedValue* field = FindObjectField(object, key);
	if (!field)
		return std::nullopt;
	if (field->kind == VansSerializedValue::Kind::Float || field->kind == VansSerializedValue::Kind::Int)
		return static_cast<float>(ReadSerializedNumber(*field));
	return std::nullopt;
}

std::optional<uint32_t> ReadOptionalUIntField(const VansSerializedValue& object, const char* key)
{
	const VansSerializedValue* field = FindObjectField(object, key);
	if (!field)
		return std::nullopt;
	if (field->kind == VansSerializedValue::Kind::Int && field->intValue >= 0)
		return static_cast<uint32_t>(field->intValue);
	return std::nullopt;
}

std::optional<bool> ReadOptionalBoolField(const VansSerializedValue& object, const char* key)
{
	const VansSerializedValue* field = FindObjectField(object, key);
	return field && field->kind == VansSerializedValue::Kind::Bool
		? std::optional<bool>(field->boolValue)
		: std::nullopt;
}

std::optional<std::string> ReadOptionalStringField(const VansSerializedValue& object, const char* key)
{
	const VansSerializedValue* field = FindObjectField(object, key);
	return field && field->kind == VansSerializedValue::Kind::String
		? std::optional<std::string>(field->stringValue)
		: std::nullopt;
}

std::optional<std::array<float, 3>> ReadOptionalFloat3Field(const VansSerializedValue& object, const char* key)
{
	const VansSerializedValue* field = FindObjectField(object, key);
	if (!field || field->kind != VansSerializedValue::Kind::Array || field->arrayItems.size() < 3)
		return std::nullopt;

	for (size_t index = 0; index < 3; ++index)
	{
		const VansSerializedValue& item = field->arrayItems[index];
		if (item.kind != VansSerializedValue::Kind::Float && item.kind != VansSerializedValue::Kind::Int)
			return std::nullopt;
	}

	return std::array<float, 3>{
		static_cast<float>(ReadSerializedNumber(field->arrayItems[0])),
		static_cast<float>(ReadSerializedNumber(field->arrayItems[1])),
		static_cast<float>(ReadSerializedNumber(field->arrayItems[2]))
	};
}

VansSceneReflectionProbeDescConfig DecodeProbe(const VansSerializedValue& probe)
{
	VansSceneReflectionProbeDescConfig config;
	config.name = ReadOptionalStringField(probe, "name");
	config.type = ReadOptionalStringField(probe, "type");
	config.shape = ReadOptionalStringField(probe, "shape");
	config.refreshMode = ReadOptionalStringField(probe, "refreshMode");
	config.position = ReadOptionalFloat3Field(probe, "position");
	config.capturePosition = ReadOptionalFloat3Field(probe, "capturePosition");
	config.boxMin = ReadOptionalFloat3Field(probe, "boxMin");
	config.boxMax = ReadOptionalFloat3Field(probe, "boxMax");
	config.radius = ReadOptionalFloatField(probe, "radius");
	config.blendDistance = ReadOptionalFloatField(probe, "blendDistance");
	config.priority = ReadOptionalFloatField(probe, "priority");
	config.intensity = ReadOptionalFloatField(probe, "intensity");
	config.specularIntensity = ReadOptionalFloatField(probe, "specularIntensity");
	config.nearPlane = ReadOptionalFloatField(probe, "nearPlane");
	config.farPlane = ReadOptionalFloatField(probe, "farPlane");
	config.resolution = ReadOptionalUIntField(probe, "resolution");
	config.cullingMask = ReadOptionalUIntField(probe, "cullingMask");
	config.regionId = ReadOptionalUIntField(probe, "regionId");
	config.facesPerFrame = ReadOptionalUIntField(probe, "facesPerFrame");
	config.enabled = ReadOptionalBoolField(probe, "enabled");
	config.boxProjection = ReadOptionalBoolField(probe, "boxProjection");
	config.autoGenerated = ReadOptionalBoolField(probe, "autoGenerated");
	config.portal = ReadOptionalBoolField(probe, "portal");
	config.cachePath = ReadOptionalStringField(probe, "cachePath");
	return config;
}
}

VansSceneReflectionProbeConfig VansSceneReflectionProbeConfigReader::Read(
	const VansSerializedValue& sceneSettings)
{
	VansSceneReflectionProbeConfig config;
	const VansSerializedValue* block = ReadObjectField(sceneSettings, "reflectionProbes");
	if (!block)
		return config;

	config.hasBlock = true;
	if (const VansSerializedValue* lighting = ReadObjectField(*block, "lighting"))
	{
		config.lighting.maxBlendCount = ReadOptionalUIntField(*lighting, "maxBlendCount");
		config.lighting.ssrRoughnessFadeStart = ReadOptionalFloatField(*lighting, "ssrRoughnessFadeStart");
		config.lighting.ssrRoughnessFadeEnd = ReadOptionalFloatField(*lighting, "ssrRoughnessFadeEnd");
		config.lighting.skyIntensity = ReadOptionalFloatField(*lighting, "skyIntensity");
	}

	if (const VansSerializedValue* placement = ReadObjectField(*block, "placement"))
	{
		config.placement.enabled = ReadOptionalBoolField(*placement, "enabled");
		config.placement.geometryOnly = ReadOptionalBoolField(*placement, "geometryOnly");
		config.placement.volumeMin = ReadOptionalFloat3Field(*placement, "volumeMin");
		config.placement.volumeMax = ReadOptionalFloat3Field(*placement, "volumeMax");
		config.placement.cellSize = ReadOptionalFloatField(*placement, "cellSize");
		config.placement.indoorSpacing = ReadOptionalFloatField(*placement, "indoorSpacing");
		config.placement.corridorSpacing = ReadOptionalFloatField(*placement, "corridorSpacing");
		config.placement.outdoorSpacing = ReadOptionalFloatField(*placement, "outdoorSpacing");
		config.placement.solidThreshold = ReadOptionalFloatField(*placement, "solidThreshold");
		config.placement.refinementThreshold = ReadOptionalFloatField(*placement, "refinementThreshold");
		config.placement.maxProbeCount = ReadOptionalUIntField(*placement, "maxProbeCount");
		config.placement.uniformSpacing = ReadOptionalFloatField(*placement, "uniformSpacing");
		config.placement.uniformBoxSizeScale = ReadOptionalFloatField(*placement, "uniformBoxSizeScale");
		config.placement.uniformProbeResolution = ReadOptionalUIntField(*placement, "uniformProbeResolution");
	}

	if (const VansSerializedValue* probes = ReadArrayField(*block, "probes"))
	{
		config.probes.reserve(probes->arrayItems.size());
		for (const VansSerializedValue& probe : probes->arrayItems)
			if (probe.kind == VansSerializedValue::Kind::Object)
				config.probes.push_back(DecodeProbe(probe));
	}

	return config;
}
}
