#pragma once

#include <array>
#include <cstdint>
#include <optional>
#include <string>
#include <vector>

namespace Vans
{
struct VansSceneReflectionProbeLightingConfig
{
	std::optional<uint32_t> maxBlendCount;
	std::optional<float> ssrRoughnessFadeStart;
	std::optional<float> ssrRoughnessFadeEnd;
	std::optional<float> skyIntensity;
};

struct VansSceneReflectionProbePlacementConfig
{
	std::optional<bool> enabled;
	std::optional<bool> geometryOnly;
	std::optional<std::array<float, 3>> volumeMin;
	std::optional<std::array<float, 3>> volumeMax;
	std::optional<float> cellSize;
	std::optional<float> indoorSpacing;
	std::optional<float> corridorSpacing;
	std::optional<float> outdoorSpacing;
	std::optional<float> solidThreshold;
	std::optional<float> refinementThreshold;
	std::optional<uint32_t> maxProbeCount;
	std::optional<float> uniformSpacing;
	std::optional<float> uniformBoxSizeScale;
	std::optional<uint32_t> uniformProbeResolution;
};

struct VansSceneReflectionProbeDescConfig
{
	std::optional<std::string> name;
	std::optional<std::string> type;
	std::optional<std::string> shape;
	std::optional<std::string> refreshMode;
	std::optional<std::array<float, 3>> position;
	std::optional<std::array<float, 3>> capturePosition;
	std::optional<std::array<float, 3>> boxMin;
	std::optional<std::array<float, 3>> boxMax;
	std::optional<float> radius;
	std::optional<float> blendDistance;
	std::optional<float> priority;
	std::optional<float> intensity;
	std::optional<float> specularIntensity;
	std::optional<float> nearPlane;
	std::optional<float> farPlane;
	std::optional<uint32_t> resolution;
	std::optional<uint32_t> cullingMask;
	std::optional<uint32_t> regionId;
	std::optional<uint32_t> facesPerFrame;
	std::optional<bool> enabled;
	std::optional<bool> boxProjection;
	std::optional<bool> autoGenerated;
	std::optional<bool> portal;
	std::optional<std::string> cachePath;
};

struct VansSceneReflectionProbeConfig
{
	bool hasBlock = false;
	VansSceneReflectionProbeLightingConfig lighting;
	VansSceneReflectionProbePlacementConfig placement;
	std::vector<VansSceneReflectionProbeDescConfig> probes;
};
}
