#pragma once

#include "VansReflectionProbe.h"
#include <algorithm>
#include <utility>

namespace VansGraphics
{
    enum class VansReflectionProbeSource : uint8_t { Authored, Generated, Override, Sky };
    struct VansReflectionProbeOrigin
    {
        VansReflectionProbeSource source = VansReflectionProbeSource::Sky;
        size_t index = 0;
    };

    // 保存的布局与派生布局具有不同所有权；切换只选择当前布局，不改写作者数据。
    class VansReflectionProbeLayout
    {
    public:
        void Reset(std::vector<VansReflectionProbeDesc> authored, std::vector<VansReflectionProbeDesc> overrides)
        {
            m_Authored = std::move(authored); m_Overrides = std::move(overrides); m_Generated.clear();
        }
        const std::vector<VansReflectionProbeDesc>& Authored() const { return m_Authored; }
        const std::vector<VansReflectionProbeDesc>& Overrides() const { return m_Overrides; }
        const std::vector<VansReflectionProbeDesc>& Generated() const { return m_Generated; }
        void SetGenerated(std::vector<VansReflectionProbeDesc> probes) { m_Generated = std::move(probes); }
        void BuildActive(bool automatic, std::vector<VansReflectionProbeDesc>& active,
            std::vector<VansReflectionProbeOrigin>& origins) const
        {
            active.clear(); origins.clear();
            auto append = [&](const std::vector<VansReflectionProbeDesc>& probes, VansReflectionProbeSource source)
            {
                for (size_t i = 0; i < probes.size(); ++i)
                {
                    if (probes[i].type == ReflectionProbeType::Sky) continue;
                    if (source == VansReflectionProbeSource::Generated && std::any_of(m_Overrides.begin(), m_Overrides.end(),
                        [&](const auto& overrideProbe) { return overrideProbe.name == probes[i].name; })) continue;
                    active.push_back(probes[i]); origins.push_back({source, i});
                }
            };
            if (automatic) { append(m_Overrides, VansReflectionProbeSource::Override); append(m_Generated, VansReflectionProbeSource::Generated); }
            else append(m_Authored, VansReflectionProbeSource::Authored);
            const auto sky = std::find_if(m_Authored.begin(), m_Authored.end(), [](const auto& p) { return p.type == ReflectionProbeType::Sky; });
            if (sky != m_Authored.end()) { active.push_back(*sky); origins.push_back({VansReflectionProbeSource::Sky, 0}); }
        }
        bool Edit(const VansReflectionProbeOrigin& origin, const VansReflectionProbeDesc& probe)
        {
            auto* target = origin.source == VansReflectionProbeSource::Authored ? &m_Authored
                : (origin.source == VansReflectionProbeSource::Override ? &m_Overrides : nullptr);
            if (!target || origin.index >= target->size() || probe.type == ReflectionProbeType::Sky) return false;
            (*target)[origin.index] = probe;
            return true;
        }
        VansReflectionProbeOrigin Pin(const VansReflectionProbeOrigin& origin, VansReflectionProbeDesc probe)
        {
            probe.autoGenerated = false;
            if (Edit(origin, probe)) return origin;
            if (origin.source == VansReflectionProbeSource::Generated)
            {
                m_Overrides.push_back(std::move(probe));
                return {VansReflectionProbeSource::Override, m_Overrides.size() - 1};
            }
            return origin;
        }
        void UpdateCachePath(const VansReflectionProbeOrigin& origin, const std::string& path)
        {
            auto* target = origin.source == VansReflectionProbeSource::Authored ? &m_Authored
                : (origin.source == VansReflectionProbeSource::Override ? &m_Overrides
                : (origin.source == VansReflectionProbeSource::Generated ? &m_Generated : nullptr));
            if (target && origin.index < target->size()) (*target)[origin.index].cachePath = path;
        }
    private:
        std::vector<VansReflectionProbeDesc> m_Authored;
        std::vector<VansReflectionProbeDesc> m_Overrides;
        std::vector<VansReflectionProbeDesc> m_Generated;
    };
}
