#pragma once

#include <../../GLM/glm.hpp>
#include <cstdint>
#include <string>
#include <vector>

namespace VansGraphics
{
	enum class ReflectionProbeType : uint8_t { Baked, Realtime, Sky };
	enum class ReflectionProbeShape : uint8_t { Sphere, Box };
	enum class ReflectionProbeRefreshMode : uint8_t { OnLoad, OnDemand, EveryFrame, TimeSliced };
	enum class ReflectionProbeDebugView : int32_t
	{
		None, Influence, ProbeColor, SSRConfidence, RegionId, Parallax,
		FallbackOnly, SSROnly
	};

	struct ReflectionProbePlacementSettings
	{
		bool enabled = true;
		bool geometryOnly = true;
		glm::vec3 volumeMin = glm::vec3(-20.0f, -14.0f, -20.0f);
		glm::vec3 volumeMax = glm::vec3(20.0f, 26.0f, 20.0f);
		float cellSize = 4.0f;
		float indoorSpacing = 8.0f;
		float corridorSpacing = 8.0f;
		float outdoorSpacing = 28.0f;
		float solidThreshold = 0.25f;
		float refinementThreshold = 0.05f;
		uint32_t maxProbeCount = 256;
		// Uniform grid placement spacing.  When > 0, GenerateAutoProbes
		// produces a regular 3D grid inside [volumeMin, volumeMax] instead
		// of the adaptive geometry-aware pipeline.
		float uniformSpacing = 7.0f;
		// Influence-box edge length relative to each uniform grid cell.
		// This does not change probe count or capture positions.
		float uniformBoxSizeScale = 1.0f;
		uint32_t uniformProbeResolution = 64;
	};

	struct ReflectionProbeLightingSettings
	{
		uint32_t maxBlendCount = 4;
		float ssrRoughnessFadeStart = 0.35f;
		float ssrRoughnessFadeEnd = 0.75f;
		float skyIntensity = 1.0f;
	};

	enum class ProbeCellClass : uint8_t { Unknown, Solid, Empty, Boundary, Exterior };
	enum class ProbeRegionType : uint8_t { Interior, Exterior, Corridor, Portal };

	struct ProbePlacementCell
	{
		ProbeCellClass cellClass = ProbeCellClass::Unknown;
		uint32_t regionId = 0xffffffffu;
		float solidFraction = 0.0f;
		float surfaceArea = 0.0f;
		float occlusion = 0.0f;
		glm::vec3 normalMean = glm::vec3(0.0f);
	};

	struct ReflectionProbePlacementGrid
	{
		glm::vec3 origin = glm::vec3(0.0f);
		glm::vec3 extent = glm::vec3(0.0f);
		float cellSize = 4.0f;
		glm::uvec3 dimensions = glm::uvec3(0u);
		std::vector<ProbePlacementCell> cells;
	};

	struct GeometryRegion
	{
		uint32_t id = 0;
		ProbeRegionType type = ProbeRegionType::Interior;
		glm::vec3 boundsMin = glm::vec3(0.0f);
		glm::vec3 boundsMax = glm::vec3(0.0f);
		glm::vec3 centroid = glm::vec3(0.0f);
		float volume = 0.0f;
		float meanOcclusion = 0.0f;
		float surfaceArea = 0.0f;
		float compactness = 0.0f;
		std::vector<uint32_t> cellIndices;
		std::vector<uint32_t> neighborRegionIds;
	};

	struct ProbeGeometryError
	{
		float uncoveredCellRatio = 0.0f;
		float maxDistanceToProbe = 0.0f;
		float occlusionVariance = 0.0f;
		float surfaceDensityVariance = 0.0f;
		float boundsAspectError = 0.0f;
	};

	struct VansReflectionProbeDesc
	{
		std::string name = "Reflection Probe";
		ReflectionProbeType type = ReflectionProbeType::Baked;
		ReflectionProbeShape shape = ReflectionProbeShape::Box;
		ReflectionProbeRefreshMode refreshMode = ReflectionProbeRefreshMode::OnLoad;
		glm::vec3 position = glm::vec3(0.0f);
		glm::vec3 capturePosition = glm::vec3(0.0f);
		glm::vec3 boxMin = glm::vec3(-5.0f);
		glm::vec3 boxMax = glm::vec3(5.0f);
		float radius = 10.0f;
		float blendDistance = 1.0f;
		float priority = 1.0f;
		float intensity = 1.0f;
		float specularIntensity = 1.0f;
		float nearPlane = 0.1f;
		float farPlane = 1000.0f;
		uint32_t resolution = 128;
		uint32_t cullingMask = 0xffffffffu;
		uint32_t regionId = 0xffffffffu;
		uint32_t realtimeFacesPerFrame = 1;
		bool enabled = true;
		bool boxProjection = false;
		bool autoGenerated = false;
		bool portal = false;
		std::string cachePath;
	};

	struct alignas(16) VansReflectionProbeGPU
	{
		glm::vec4 positionAndRadius;
		glm::vec4 boxMinAndType;
		glm::vec4 boxMaxAndPriority;
		glm::vec4 fadeAndIntensity;
		glm::vec4 capturePositionAndLayer;
		glm::uvec4 regionAndFlags;
		glm::vec4 specularAndMip;
	};

	struct alignas(16) ReflectionProbeBufferHeader
	{
		uint32_t probeCount = 0;
		uint32_t activeProbeCount = 0;
		uint32_t maxBlendCount = 4;
		uint32_t debugView = 0;
		glm::vec4 lightingParams = glm::vec4(0.35f, 0.75f, 1.0f, 1.0f);
		glm::vec4 uniformGridOrigin = glm::vec4(0.0f);
		glm::vec4 uniformGridInvCellSize = glm::vec4(0.0f);
		glm::uvec4 uniformGridDimensionsAndFlags = glm::uvec4(0u);
	};

	struct ReflectionProbeBakeResult
	{
		bool valid = false;
		bool dirty = true;
		uint32_t arrayLayer = 0;
		uint32_t mipCount = 1;
		uint64_t revision = 0;
		std::string cachePath;
		std::string status = "Not baked";
	};

	struct ReflectionProbeEditorState
	{
		int selectedProbeIndex = -1;
		bool showProbeGizmos = true;
		bool showInfluenceVolumes = true;
		bool showBlendVolumes = true;
		bool showPlacementGrid = false;
		bool showRegions = false;
		bool previewCubemap = false;
		int previewFace = 0;
		float previewRoughness = 0.0f;
		ReflectionProbeDebugView debugView = ReflectionProbeDebugView::None;
	};
}
