#version 450
#extension GL_GOOGLE_include_directive : require

#include "../Common/Common.glsl"

layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

layout(set = 1, binding = 0, r32f) uniform image2D hizSource;
layout(set = 1, binding = 1, r32f) uniform image2D hizResult;

void main()
{
    ivec2 pixelCoord = ivec2(gl_GlobalInvocationID.xy);
    ivec2 dstSize = imageSize(hizResult);
    ivec2 srcSize = imageSize(hizSource);
    if (pixelCoord.x >= dstSize.x || pixelCoord.y >= dstSize.y)
        return;

    ivec2 srcCoord = pixelCoord * 2;
    float d0 = imageLoad(hizSource, clamp(srcCoord,               ivec2(0), srcSize - 1)).r;
    float d1 = imageLoad(hizSource, clamp(srcCoord + ivec2(1, 0), ivec2(0), srcSize - 1)).r;
    float d2 = imageLoad(hizSource, clamp(srcCoord + ivec2(0, 1), ivec2(0), srcSize - 1)).r;
    float d3 = imageLoad(hizSource, clamp(srcCoord + ivec2(1, 1), ivec2(0), srcSize - 1)).r;

    float maxDepth = max(max(d0, d1), max(d2, d3));
    imageStore(hizResult, pixelCoord, vec4(maxDepth, 0.0, 0.0, 0.0));
}
