#pragma once

bool TestGAFGameplayTagsContract();
bool TestGAFAttributesContract();
bool TestGAFCuesAndEffectsContract();
bool TestGAFTargetingContract();
bool TestGAFDefinitionAndServiceContract();
bool TestGAFResourceLedgerAndTaskContract();
bool TestGAFExecutionGraphContract();
bool TestGAFActionHostLifecycleContract();
bool TestGAFAssetSchemaAndCookContract();
bool TestGAFPackagingContract();
bool TestGAFNetworkContract();
bool TestGAFDebugAndReplayContract();
bool TestGAFSampleLibraryContract();
bool TestGAFDemoHallWindowBreakContract();
bool TestGAFDemoHallPlayerAttackContract();
bool TestDemoHallCrouchLocomotionContract();
bool TestDemoHallPlayerVaultContract();
bool TestDemoHallWhisperPreviewContract();
bool TestGAFLuaBridgeContract();
