#!/usr/bin/env python3
# =============================================================================
# generate_ltc_data.py
#
# Fetches the LTC fit results from selfshadow/ltc_code (MIT) and emits
# LTCData.generated.inl next to this script. The .inl provides the bodies of
# the two arrays declared in LTCData.h:
#
#   const float VansGraphics::LTC::kLTC1[kLUTFloats] = { ... };
#   const float VansGraphics::LTC::kLTC2[kLUTFloats] = { ... };
#
# Each array contains 64 * 64 * 4 = 16384 single-precision floats, row-major,
# matching the WebGL demo's parametrisation (uv.x = sqrt(1 - NoV), uv.y = roughness).
#
# Run once after first checkout (or when upgrading LTC fits):
#
#       python Source/EngineCore/RenderCore/LTC/generate_ltc_data.py
#
# No external Python packages are required (uses only the standard library).
# =============================================================================
import os
import re
import sys
import urllib.request

LTC_JS_URL = "https://raw.githubusercontent.com/selfshadow/ltc_code/master/fit/results/ltc.js"
EXPECTED_FLOATS = 64 * 64 * 4  # 16384

OUT_FILE = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                        "LTCData.generated.inl")


def fetch_ltc_js() -> str:
    print(f"[LTC] Downloading {LTC_JS_URL}")
    with urllib.request.urlopen(LTC_JS_URL, timeout=30) as resp:
        return resp.read().decode("utf-8")


def extract_array(js_text: str, name: str) -> list:
    """Pull `var <name> = [ ... ];` (or `const <name> = ...`) from the JS source."""
    pattern = re.compile(
        r"\b" + re.escape(name) + r"\s*=\s*\[(?P<body>[^\]]+)\]",
        re.DOTALL,
    )
    m = pattern.search(js_text)
    if not m:
        raise RuntimeError(f"Could not locate array '{name}' in ltc.js")
    body = m.group("body")
    floats = [float(t) for t in re.findall(r"[-+]?\d*\.\d+(?:[eE][-+]?\d+)?|[-+]?\d+(?:[eE][-+]?\d+)?", body)]
    if len(floats) != EXPECTED_FLOATS:
        raise RuntimeError(
            f"Expected {EXPECTED_FLOATS} floats in '{name}', got {len(floats)}"
        )
    return floats


def emit_array(out, cpp_name: str, values: list, per_line: int = 8):
    out.write(f"const float VansGraphics::LTC::{cpp_name}[VansGraphics::LTC::kLUTFloats] = {{\n")
    for i in range(0, len(values), per_line):
        chunk = values[i : i + per_line]
        out.write("    " + ", ".join(f"{v: .8e}f" for v in chunk) + ",\n")
    out.write("};\n\n")


def main() -> int:
    js = fetch_ltc_js()
    ltc1 = extract_array(js, "g_ltc_1")
    ltc2 = extract_array(js, "g_ltc_2")

    print(f"[LTC] Writing {OUT_FILE}")
    with open(OUT_FILE, "w", encoding="ascii", newline="\n") as out:
        out.write("// Auto-generated by Source/EngineCore/RenderCore/LTC/generate_ltc_data.py\n")
        out.write("// DO NOT EDIT BY HAND. Regenerate by re-running the script.\n")
        out.write("// Source: selfshadow/ltc_code  (MIT License)\n\n")
        emit_array(out, "kLTC1", ltc1)
        emit_array(out, "kLTC2", ltc2)

    print(f"[LTC] Done. {EXPECTED_FLOATS * 2} floats written.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
